ccflags-y += ${PROJECTINCLUDE} \
-I${ZEPHYR_BASE}/nvisionit/x86_app \
-I${ZEPHYR_BASE}/nvisionit/common \
-I$(ZEPHYR_BASE)/include/drivers \
-I$(ZEPHYR_BASE)/drivers

obj-y = main.o \
../../gatt/gap.o \
../../gatt/hrs.o \
../../gatt/dis.o \
../../gatt/bas.o \
../../gatt/aios.o \
../../gatt/ess.o
